### ISSUE TITLE
Изменение конфигурации виртуальной машины без необходимости ручной остановки.

### ISSUE THREAD

**Issue by Geexmo** [T1Cloud/terraform-provider-t1cloud#11]
Всем привет!
На данный момент при попытке изменить тип виртуальной машины ее необходимо предварительно остановить из консоли:
terraform plan:
<img width="922" alt="image" src="https://github.com/T1Cloud/terraform-provider-t1cloud/assets/49608464/ae640654-c4d4-407e-b42d-6fd910c9b43f">
Ожидаемое поведение:
При изменении типа ресурсов провайдер корректно обработает ситуацию и рестартнет виртуальную машину самостоятельно.

После выключения виртуальной машины, все равно требуется менять tfstate ибо провайдер опирается на то, что машина все еще в state on:
<img width="870" alt="image" src="https://github.com/T1Cloud/terraform-provider-t1cloud/assets/49608464/16382d6e-ce0d-464e-b1a4-474f5b2366e8">

**Comment by Ichi-1** [comment]
> После выключения виртуальной машины, все равно требуется менять tfstate ибо провайдер опирается на то, что машина все еще в state on

Видимо, скрин перепутан. После остановки виртуальной машины, вам не обязательно вносить изменения в tfstate,  если вы выполнили данное действие через провайдер, т.к. в вашем конфиге явно указано state = off.


> Ожидаемое поведение:
> При изменении типа ресурсов провайдер корректно обработает ситуацию и рестартнет виртуальную машину самостоятельно.
Предположим, что при изменении flavor провайдер выполняет остановку перед ресайзом и запуск после ресайза. Варианты ожидаемого поведения

1. ВМ уже остановлена - остановка не требуется, флейвор будет изменен. После ресайза, ВМ останется в выключенном состоянии.
```
state = off
flavor = *changed*
```


2. ВМ остановлена, но планируется к включению. Флейвор будет изменен, ВМ будет запущена.
```
state = off -> on
flavor = *changed*
```


3. ВМ не остановлена. ВМ будет принудительно остановлена на момент ресайза, а затем запущена.
```
state = on 
flavor = *changed*
```

4. ВМ запущена, но планируется к выключению. После ресайза, ВМ останется в выключенном состоянии.
```
state = on -> off
flavor = *changed*
```

**Comment by Geexmo** [comment]
Если я правильно понимаю, то третий пункт должен отработать корректно.
Вм state = on
<img width="1324" alt="image" src="https://github.com/T1Cloud/terraform-provider-t1cloud/assets/49608464/3427a61e-b1ff-4315-b524-4248f474e944">
terraform plan по resize:
<img width="844" alt="image" src="https://github.com/T1Cloud/terraform-provider-t1cloud/assets/49608464/03c76309-a207-4ae5-8eb7-e7159d921dc4">
И наконец деплой:
<img width="1118" alt="image" src="https://github.com/T1Cloud/terraform-provider-t1cloud/assets/49608464/8c390c5e-dc0d-4052-b4f6-19d3d0f814f7">

Машину описываем примерно так:
```
  {   
    vm_name                       = "jira"
    vm_core_amount                = 4
    vm_memory_gb                  = 16
    vm_boot_volume_size           = 40
    vm_disk_delete_on_termination = true
    vm_disk_type                  = "Basic"                                                                        
    vm_fixed_ip                   = "10.100.1.96"
    vm_custom_image_id            = "AlmaLinux8v2"
    vm_subnet_id                  = "common-services"
    vm_security_group_ids         = ["e935a50b-dbb8-4199-97d6-325a58feeb3f", "7381222b-5a1c-4dd7-a77f-2ba9d309dc6d"]
    vm_cpu_series                 = "default"
  },
```

Что ожидаем? Что провайдер стопнет машину, произведет resize и включит обратно.

**Comment by Ichi-1** [comment]
> провайдер стопнет машину, произведет resize и включит обратно.

Изначально, когда ресурс не поддерживал атрибут state, провайдер реализовывал описанное поведение. С добавление параметра state, позволяющего явно контролировать состояние ВМ, данное поведение было изменено на текущее, когда state указывается явно, в том числе off для ресайза.

**Comment by Geexmo** [comment]
> > провайдер стопнет машину, произведет resize и включит обратно.
> 
> Изначально, когда ресурс не поддерживал атрибут state, провайдер реализовывал описанное поведение. С добавление параметра state, позволяющего явно контролировать состояние ВМ, данное поведение было изменено на текущее, когда state указывается явно, в том числе off для ресайза.

Получается путь такой, что нужно в модуль добавить state, переводить его в off для ресайза и потом снова в on? То есть для resize'а потенциально требуется два коммита?

**Comment by Ichi-1** [comment]
> > > провайдер стопнет машину, произведет resize и включит обратно.
> > 
> > 
> > Изначально, когда ресурс не поддерживал атрибут state, провайдер реализовывал описанное поведение. С добавление параметра state, позволяющего явно контролировать состояние ВМ, данное поведение было изменено на текущее, когда state указывается явно, в том числе off для ресайза.
> 
> Получается путь такой, что нужно в модуль добавить state, переводить его в off для ресайза и потом снова в on? То есть для resize'а потенциально требуется два коммита?

Соглашусь, что это может быть неудобно в некоторых сценариях автоматизации.

**Comment by Geexmo** [comment]
> > > > провайдер стопнет машину, произведет resize и включит обратно.
> > > 
> > > 
> > > Изначально, когда ресурс не поддерживал атрибут state, провайдер реализовывал описанное поведение. С добавление параметра state, позволяющего явно контролировать состояние ВМ, данное поведение было изменено на текущее, когда state указывается явно, в том числе off для ресайза.
> > 
> > 
> > Получается путь такой, что нужно в модуль добавить state, переводить его в off для ресайза и потом снова в on? То есть для resize'а потенциально требуется два коммита?
> 
> Соглашусь, что это может быть неудобно в некоторых сценариях автоматизации.

Вот отсюда и исходит issue, как мы действуем? terraform plan исполняется только на моменте merge request'a, apply только после мержа, достаточно дефолтный сценарий. То есть требуется 2 mr'a как минимум для ресайза. Тут предложение, либо возвращение сценария "до", либо имеет смысл сценарий ручного выключения ВМ и ее включения терраформом после ресайза. Может у вас есть какие-нибудь идеи? Добавлять к куче ВМ атрибут state кажется странным, ибо state должен только в tfstate как по мне храниться, а не описываться в коде.

**Comment by Ichi-1** [comment]
> Добавлять к куче ВМ атрибут state кажется странным, ибо state должен только в tfstate как по мне храниться, а не описываться в коде.

Параметр **state** был добавлен для возможности включения и выключения ВМ. 
Если сделать данное поле Read Only, то данный нужно переосмыслить возможность вкл/выкл ВМки через провайдер. 

>Может у вас есть какие-нибудь идеи?
Автоматический ресайз с принудительным перезапуском может быть реализован, поэтому я и уточнил по ожидаемому поведению при комбинировании различных вариантов параметра **state** при изменении flavor

**Comment by Ichi-1** [comment]
Предложение взято в доработку провайдера
