### ISSUE TITLE
Ошибка при terraform destroy

### ISSUE THREAD

**Issue by ant1freeze** [T1Cloud/terraform-provider-t1cloud#18]
Если при создании манифеста (в котором создается машина, добавляется ключ, выделяется ip, привязывается ip и привязываются правила безопасности) добавить ресурс:
```
resource "t1_vpc_public_ip" "public_ip_test" {
    region = "ru-central1"
}
```

то при terraform destroy выскакивает ошибка 
(после удаления некоторых ресурсов, таких как
t1_compute_floating_ip_associate, 
t1_compute_instance.vm_test 
итд; 
причем в списке ресурсов, которые удалились присутствует и t1_vpc_public_ip.public_ip_test: Destroying...  но нет Destruction complete):
```
│ Error: Resource destruction failed:
│
│ request was failed with status 404 Not Found. Error message: {"error":{"code":"action_not_found"}}
```

При повторном запуске terraform destroy предлагается удалить  t1_vpc_public_ip.public_ip_test и после подтверждения - все ок.

Проблема в том, что дестрой приходится запускать дважды, так как с первого раза он не может удалить публичный адрес, который выдал.

**Comment by ant1freeze** [comment]
То есть это нормальное поведение?
На самом деле, если да, то и ничего критичного в повторном запуске нет, просто странно немного.
Я пользовался и яндексом и aws и do - там destroy удаляет все за один раз.

**Comment by Ichi-1** [comment]
> То есть это нормальное поведение?

По крайней мере, я бы не стал утверждать, что это именно желаемое поведение для некоторых сценариев автоматизации (конечно, в один проход сделать удобнее), но в настоящий момент оно является нормальным. 

>Я пользовался и яндексом и aws и do - там destroy удаляет все за один раз.

Насчет aws и яндекс.клауд провайдера - эти провайдеры написаны с использованием клиентов к API OpenStack, наш провайдер же использует клиент к API T1.Cloud, т.е. не обращается на прямую в облако. В связи с этим возникают подобного рода ограничения при проектировании и эксплуатации провайдера.

**Comment by ant1freeze** [comment]
Ок. Закрываем, спасибо за подробные ответы.
